<?php
/**
 * Exports ACtions
 *
 * These are actions related to exporting data from pl8app.
 *
 * @package     pl8app
 * @subpackage  Admin/Export
 * @copyright
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Process the menuitem file generated by a batch export
 *
 * @since 2.4
 * @return void
 */
function pl8app_process_batch_export_menuitem() {

	if( ! wp_verify_nonce( $_REQUEST['nonce'], 'pl8app-batch-export' ) ) {
		wp_die( __( 'Nonce verification failed', 'pl8app' ), __( 'Error', 'pl8app' ), array( 'response' => 403 ) );
	}

	require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export.php';

	do_action( 'pl8app_batch_export_class_include', $_REQUEST['class'] );

	$export = new $_REQUEST['class'];
	$export->export();

}
add_action( 'pl8app_menuitem_batch_export', 'pl8app_process_batch_export_menuitem' );

/**
 * Export all the customers to a CSV file.
 *
 * Note: The WordPress Database API is being used directly for performance
 * reasons (workaround of calling all posts and fetch data respectively)
 *
 * @since  1.0.0
 * @return void
 */
function pl8app_export_all_customers() {
	require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/class-export-customers.php';

	$customer_export = new pl8app_Customers_Export();

	$customer_export->export();
}
add_action( 'pl8app_email_export', 'pl8app_export_all_customers' );

/**
 * Exports all the menuitems to a CSV file using the pl8app_Export class.
 *
 * @since  1.0.0
 * @return void
 */
function pl8app_export_all_menuitems_history() {
	require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/class-export-menuitem-history.php';

	$file_menuitem_export = new pl8app_pl8app_History_Export();

	$file_menuitem_export->export();
}
add_action( 'pl8app_menuitems_history_export', 'pl8app_export_all_menuitems_history' );

/**
 * Add a hook allowing extensions to register a hook on the batch export process
 *
 * @since 1.0
 * @return void
 */
function pl8app_register_batch_exporters() {
	if ( is_admin() ) {
		do_action( 'pl8app_register_batch_exporter' );
	}
}
add_action( 'plugins_loaded', 'pl8app_register_batch_exporters', 99 );

/**
 * Register the payments batch exporter
 * @since 1.0
 */
function pl8app_register_payments_batch_export() {
	add_action( 'pl8app_batch_export_class_include', 'pl8app_include_payments_batch_processer', 10, 1 );
}
add_action( 'pl8app_register_batch_exporter', 'pl8app_register_payments_batch_export', 10 );

/**
 * Loads the payments batch process if needed
 *
 * @since 1.0
 * @param  string $class The class being requested to run for the batch export
 * @return void
 */
function pl8app_include_payments_batch_processer( $class ) {

	if ( 'pl8app_Batch_Payments_Export' === $class ) {
		require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-payments.php';
	}

}

/**
 * Register the customers batch exporter
 * @since 1.0
 */
function pl8app_register_customers_batch_export() {
	add_action( 'pl8app_batch_export_class_include', 'pl8app_include_customers_batch_processer', 10, 1 );
}
add_action( 'pl8app_register_batch_exporter', 'pl8app_register_customers_batch_export', 10 );

/**
 * Loads the customers batch process if needed
 *
 * @since 1.0
 * @param  string $class The class being requested to run for the batch export
 * @return void
 */
function pl8app_include_customers_batch_processer( $class ) {

	if ( 'pl8app_Batch_Customers_Export' === $class ) {
		require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-customers.php';
	}

}

/**
 * Register the menuitem products batch exporter
 *
 * @since  1.0.0
 */
function pl8app_register_menuitems_batch_export() {
	add_action( 'pl8app_batch_export_class_include', 'pl8app_include_menuitems_batch_processer', 10, 1 );
}
add_action( 'pl8app_register_batch_exporter', 'pl8app_register_menuitems_batch_export', 10 );

/**
 * Loads the file menuitems batch process if needed
 *
 * @since  1.0.0
 * @param  string $class The class being requested to run for the batch export
 * @return void
 */
function pl8app_include_menuitems_batch_processer( $class ) {

	if ( 'pl8app_Batch_pl8app_Export' === $class || 'pla8pp_Batch_pl8app_category_Export' === $class || 'pla8pp_Batch_pl8app_addon_Export' === $class) {
		require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-menuitems.php';
	}
}

/**
 * Register the file menuitems batch exporter
 * @since 1.0
 */
function pl8app_register_file_menuitems_batch_export() {
	add_action( 'pl8app_batch_export_class_include', 'pl8app_include_file_menuitems_batch_processer', 10, 1 );
}
add_action( 'pl8app_register_batch_exporter', 'pl8app_register_file_menuitems_batch_export', 10 );

/**
 * Loads the file menuitems batch process if needed
 *
 * @since 1.0
 * @param  string $class The class being requested to run for the batch export
 * @return void
 */
function pl8app_include_file_menuitems_batch_processer( $class ) {

	if ( 'pl8app_Batch_File_Orders_Export' === $class ) {
		require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-orders.php';
	}
}

/**
 * Register the sales batch exporter
 *
 * @since 1.0
 */
function pl8app_register_sales_export_batch_export() {
	add_action( 'pl8app_batch_export_class_include', 'pl8app_include_sales_export_batch_processer', 10, 1 );
}
add_action( 'pl8app_register_batch_exporter', 'pl8app_register_sales_export_batch_export', 10 );

/**
 * Loads the sales export batch process if needed
 *
 * @since 1.0
 * @param  string $class The class being requested to run for the batch export
 * @return void
 */
function pl8app_include_sales_export_batch_processer( $class ) {
	if ( 'pl8app_Batch_Sales_Export' === $class ) {
		require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-sales.php';
	}
}

/**
 * Register the earnings report batch exporter
 *
 * @since 1.0
 */
function pl8app_register_earnings_report_batch_export() {
	add_action( 'pl8app_batch_export_class_include', 'pl8app_include_earnings_report_batch_processer', 10, 1 );
}
add_action( 'pl8app_register_batch_exporter', 'pl8app_register_earnings_report_batch_export', 10 );

/**
 * Loads the earnings report batch process if needed
 *
 * @since 1.0
 * @param  string $class The class being requested to run for the batch export
 * @return void
 */
function pl8app_include_earnings_report_batch_processer( $class ) {
	if ( 'pl8app_Batch_Earnings_Report_Export' === $class ) {
		require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-earnings-report.php';
	}
}

/**
 * Register the API requests batch exporter
 *
 * @since 1.0
 */
function pl8app_register_api_requests_batch_export() {
	add_action( 'pl8app_batch_export_class_include', 'pl8app_include_api_requests_batch_processer', 10, 1 );
}
add_action( 'pl8app_register_batch_exporter', 'pl8app_register_api_requests_batch_export', 10 );

/**
 * Loads the API requests batch process if needed
 *
 * @since 1.0
 * @param  string $class The class being requested to run for the batch export
 * @return void
 */
function pl8app_include_api_requests_batch_processer( $class ) {
	if ( 'pl8app_Batch_API_Requests_Export' === $class ) {
		require_once PL8_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-api-requests.php';
	}
}
